#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Running lint checks
yarn lint

# Running unit tests
yarn test

# Running fast checks last to ensure quick feedback on more common issues
yarn g:run-fast-checks
